from enum import Enum


class ClientResponseTypes(Enum):
    REGULAR_TEXT_MESSAGE = '1001'
    MESSAGE_RECEIVED_RESPONSE = '1002'
    EVERYTHING_OK = '1003'
    MISSING_MESSAGE = '1004'
    USERNAME_GIVEN = '1005'
    PASSCODE_GIVEN = '1006'
    CLIENT_DISCONNECTED = '1007'


class ServerResponseTypes(Enum):
    PASSCODE_INCORRECT = '2001'
    PASSCODE_CORRECT = '2002'
    USERNAME_INCORRECT = '2003'
    USERNAME_ACCEPTED = '2004'
    MESSAGE_RECEIVED_BY_THE_SERVER = '2005'
    MESSAGE_RECEIVED_BY_CLIENT = '2006'
    MISSING_MESSAGE_FOUND = '2007'
    MESSAGE_FROM_CLIENT = '2008'


class ServerEventTypes(Enum):
    STARTING = "STARTING"
    STARTED = "STARTED"
    LISTENING = "LISTENING"
    ATTEMPTED_CONNECTION = "ATTEMPTED_CONNECTION"
    NEW_CLIENT = "NEW_CLIENT"
    ACTIVE_CLIENTS = "ACTIVE_CLIENTS"
    CLIENT_DISCONNECTED = "CLIENT_DISCONNECTED"
    MESSAGE_RECEIVED = "MESSAGE_RECEIVED"
    MESSAGE_DISPATCHED = "MESSAGE_DISPATCHED"
    MESSAGED_DELIVERED = "MESSAGED_DELIVERED"
    MISSING_MESSAGE = "MISSING_MESSAGE"
    SHUTTING_DOWN = "SHUTTING_DOWN"
